CREATE TABLE TEMPORAL (
  NOMBRE_VICTIMA VARCHAR(60),
  APELLIDO_VICTIMA VARCHAR(60),
  DIRECCION_VICTIMA VARCHAR(100),
  FECHA_PRIMERA_SOSPECHA DATE,
  FECHA_CONFIRMACION DATE,
  FECHA_MUERTE DATE,
  ESTADO_VICTIMA VARCHAR(60),
  NOMBRE_ASOCIADO VARCHAR(60),
  APELLIDO_ASOCIADO VARCHAR(60),
  FECHA_CONOCIO  DATE,
  CONTACTO_FISICO VARCHAR(60),
  FECHA_INICIO_CONTACTO DATE ,
  FECHA_FIN_CONTACTO DATE ,
  NOMBRE_HOSPITAL VARCHAR(60),
  DIRECCION_HOSPITAL VARCHAR(100),
  UBICACION_VICTIMA VARCHAR(100),
  FECHA_LLEGADA DATE,
  FECHA_RETIRO DATE,
  TRATAMIENTO VARCHAR(60),
  EFECTIVIDAD int,
  FECHA_INICIO_TRATAMIENTO DATE,
  FECHA_FIN_TRATAMIENTO DATE,
  EFECTIVIDAD_EN_VICTIMA INT
);
SELECT * FROM temporal;
DROP TABLE temporal;


--TABLAS ******************************************************************
--Ubicacion
CREATE TABLE Ubicacion(
    id_ubicacion INTEGER GENERATED BY DEFAULT as identity (START WITH 1 INCREMENT BY 1) ,
    ubicacion VARCHAR(60),
    CONSTRAINT pk_ubicacion PRIMARY KEY(id_ubicacion)
);

--Tratamiento
CREATE TABLE Tratamiento (
    id_tratamiento INTEGER GENERATED BY DEFAULT as identity (START WITH 1 INCREMENT BY 1) ,
    nombre VARCHAR(50),
    efectividad int,
    PRIMARY KEY(id_tratamiento)
);

--tipo contacto
CREATE Table Tipo_contacto(
    id_tipocontacto INTEGER GENERATED BY DEFAULT as identity (START WITH 1 INCREMENT BY 1) ,
    tipo_contacto VARCHAR(50),
    PRIMARY key(id_tipocontacto)
);

--Allegado
CREATE Table Allegado(
    id_allegado INTEGER GENERATED BY DEFAULT as identity (START WITH 1 INCREMENT BY 1) ,
    nombre VARCHAR(50),
    apellido VARCHAR(50),
    PRIMARY KEY(id_allegado)
);
--Tabla Hospital
CREATE TABLE Hospital (
    id_hospital INTEGER GENERATED BY DEFAULT as identity (START WITH 1 INCREMENT BY 1) ,
    nombre VARCHAR(60),
    id_ubicacion int, 
    PRIMARY KEY (id_hospital),
    FOREIGN KEY (id_ubicacion) REFERENCES Ubicacion(id_ubicacion) 
);

--Tabla victima 
CREATE TABLE Victima (
    id_victima INTEGER GENERATED BY DEFAULT as identity (START WITH 1 INCREMENT BY 1) ,
    nombre VARCHAR(60),
    apellido VARCHAR(60),
    id_direccion int,
    fecha_primera_sospecha date,
    fecha_confirmacion date,
    fecha_muerte date,
    status_enfermedad VARCHAR(50),
    PRIMARY key(id_victima),
    FOREIGN KEY (id_direccion) REFERENCES Ubicacion(id_ubicacion)
);

--Tabla Registro (Hospital-victima)
CREATE TABLE Registro(
    id_registro INTEGER GENERATED BY DEFAULT as identity (START WITH 1 INCREMENT BY 1) ,
    id_hospital int,
    id_victima int,
    PRIMARY KEY(id_registro),
    FOREIGN KEY (id_hospital) REFERENCES Hospital(id_hospital) ,
    FOREIGN KEY (id_victima) REFERENCES victima(id_victima) 
);


--victima-tratamiento
CREATE TABLE victima_tratamiento(
    id_p_tratamiento INTEGER GENERATED BY DEFAULT as identity (START WITH 1 INCREMENT BY 1) ,
    id_victima int,
    id_tratamiento int,
    efectividad_en_victima int,
    FECHA_INICIO_TRATAMIENTO DATE,
    FECHA_FIN_TRATAMIENTO DATE,
    PRIMARY KEY(id_p_tratamiento),
    FOREIGN KEY (id_victima) REFERENCES victima(id_victima),
    FOREIGN KEY (id_tratamiento) REFERENCES Tratamiento(id_tratamiento)
);

DROP TABLE VICTIMA_TRATAMIENTO ;
--Lugar_victima  (lugares que un victima visito)
CREATE TABLE Lugar_victima(
	id_lugarvictima INTEGER GENERATED BY DEFAULT as identity (START WITH 1 INCREMENT BY 1) ,
    id_ubicacion int,
    id_victima int,
    fecha_llegada date,
    fecha_retiro date,
    PRIMARY KEY(id_lugarvictima),
    FOREIGN KEY (id_ubicacion) REFERENCES Ubicacion(id_ubicacion),
    FOREIGN KEY (id_victima) REFERENCES VICTIMA(id_victima)
);

--Contacto (Allegado victima)
CREATE Table Allegado_victima(
    id_allegadovictima INTEGER GENERATED BY DEFAULT as identity (START WITH 1 INCREMENT BY 1) ,
    id_victima int,
    id_allegado int,
    id_tipocontacto int,
    fecha_conocio date,
    fecha_inicio_contacto date,
    fecha_fin_contacto date,
    PRIMARY KEY(id_allegadovictima),
    FOREIGN KEY (id_victima) REFERENCES victima(id_victima),
    FOREIGN KEY (id_allegado) REFERENCES Allegado(id_allegado),
    FOREIGN KEY (id_tipocontacto) REFERENCES Tipo_contacto(id_tipocontacto)
);

--RELLENAR TABLAS******************************************************************
DROP TABLE Ubicacion CASCADE CONSTRAINTS;
DROP TABLE TRATAMIENTO CASCADE CONSTRAINTS;
DROP Table tipo_contacto CASCADE CONSTRAINTS;
drop Table Allegado CASCADE CONSTRAINTS;
DROP TABLE hospital  CASCADE CONSTRAINTS;
DROP TABLE Victima CASCADE CONSTRAINTS;
DROP TABLE REGISTRO CASCADE CONSTRAINTS;
DROP TABLE victima_tratamiento CASCADE CONSTRAINTS;
DROP TABLE Lugar_victima CASCADE CONSTRAINTS;
DROP TABLE Allegado_victima CASCADE CONSTRAINTS;


SELECT table_name FROM all_tables;
--------------------------
-- Insertar Ubicaciones --
--------------------------
INSERT INTO Ubicacion(ubicacion)
SELECT DISTINCT temporal.direccion_victima FROM TEMPORAL union
select DISTINCT temporal.direccion_hospital FROM temporal union
select DISTINCT temporal.ubicacion_victima FROM TEMPORAL
WHERE 
    temporal.direccion_victima is not null AND 
    temporal.direccion_hospital is not null AND 
    temporal.ubicacion_victima is not null 
;

SELECT * FROM ubicacion
ORDER by id_ubicacion;

--------------------------
---Insertar Tratamiento---
--------------------------
INSERT INTO Tratamiento (nombre,efectividad) 
SELECT DISTINCT
    temporal.TRATAMIENTO,
    temporal.EFECTIVIDAD
FROM temporal
WHERE 
    temporal.tratamiento is not null AND 
    temporal.EFECTIVIDAD is not null
;
SELECT * FROM Tratamiento
ORDER by id_tratamiento;

----------------------------
---Insertar Tipo Contacto---
----------------------------
INSERT INTO Tipo_contacto(tipo_contacto) 
SELECT DISTINCT
    temporal.CONTACTO_FISICO
FROM temporal
WHERE 
    temporal.CONTACTO_FISICO is not null
;
SELECT * FROM Tipo_contacto
ORDER by id_tipocontacto;

----------------------------
--Insertar Allegado--
----------------------------
INSERT INTO ALLEGADO(nombre,apellido) 
SELECT DISTINCT 
    TEMPORAL.NOMBRE_ASOCIADO,
    TEMPORAL.APELLIDO_ASOCIADO
FROM TEMPORAL
WHERE 
    TEMPORAL.NOMBRE_ASOCIADO is not null
;
SELECT * FROM ALLEGADO 
ORDER by id_allegado;

SELECT * FROM TEMPORAL;
-------------------------
---Insertar Hospitales---
-------------------------
INSERT INTO Hospital (id_ubicacion, nombre) 
SELECT DISTINCT
    ubicacion.id_ubicacion,   --tomar id de la ubicacion
    temporal.NOMBRE_HOSPITAL --tomar el nombre del hospital
FROM Temporal, Ubicacion
WHERE 
    temporal.NOMBRE_HOSPITAL is not null AND --que el nombre del hospital no sea nulo
    --BUSCA LA FILA DE UBICACION CON LA CONCIDENCIA Y LA REGRESA PARA EL DISTINCT
    temporal.DIRECCION_HOSPITAL = Ubicacion.ubicacion --tomar el id_ubicacion donde ubicacion sea igual a direccion hospital
;
SELECT * FROM Hospital
ORDER BY id_hospital;

-----------------------
-- Insertar Victima --
-----------------------
INSERT INTO Victima (nombre, apellido, id_direccion, fecha_primera_sospecha, fecha_confirmacion, fecha_muerte,status_enfermedad) 
SELECT DISTINCT 
       temporal.NOMBRE_VICTIMA,
       temporal.APELLIDO_VICTIMA,
       ubicacion.id_ubicacion,
       temporal.FECHA_PRIMERA_SOSPECHA,
       temporal.FECHA_CONFIRMACION,
       TEMPORAL.FECHA_MUERTE,
       TEMPORAL.ESTADO_VICTIMA
FROM temporal, Ubicacion
WHERE
   TEMPORAL.DIRECCION_VICTIMA = Ubicacion.ubicacion
;
SELECT * FROM Victima ORDER BY ID_VICTIMA ;

----------------------
-- Insertar Registro (Hospital-victima) --
----------------------
INSERT INTO Registro(id_hospital,id_victima)
SELECT DISTINCT 
    Hospital.id_hospital,
    victima.id_victima
FROM Temporal, Hospital, victima 
WHERE 
    temporal.NOMBRE_HOSPITAL = Hospital.nombre and
    temporal.NOMBRE_VICTIMA = Victima.nombre AND 
    TEMPORAL.APELLIDO_VICTIMA = Victima.APELLIDO 
    ;
DELETE FROM REGISTRO;
SELECT * FROM Registro ORDER BY ID_REGISTRO ;


----------------------------------
-- Insertar Victima-tratamiento --
----------------------------------
INSERT INTO victima_tratamiento(id_victima,id_tratamiento,efectividad_en_victima,FECHA_INICIO_TRATAMIENTO,FECHA_FIN_TRATAMIENTO)
SELECT DISTINCT 
    Victima.id_victima,
    Tratamiento.id_tratamiento,
    TEMPORAL.EFECTIVIDAD_EN_VICTIMA,
    TEMPORAL.FECHA_INICIO_TRATAMIENTO,
    TEMPORAL.FECHA_FIN_TRATAMIENTO
FROM Temporal, TRATAMIENTO, victima 
WHERE 
	TEMPORAL.NOMBRE_VICTIMA = VICTIMA.NOMBRE AND
	TEMPORAL.APELLIDO_VICTIMA = VICTIMA.APELLIDO AND 
    TEMPORAL.TRATAMIENTO = TRATAMIENTO.NOMBRE ;
SELECT COUNT(*) FROM VICTIMA_TRATAMIENTO; 
DELETE FROM VICTIMA_TRATAMIENTO;
SELECT * FROM victima_tratamiento ORDER BY ID_P_TRATAMIENTO ;

----------------------------
---Insertar Lugar_victima---
----------------------------
INSERT INTO Lugar_victima(id_victima,id_ubicacion,fecha_llegada,fecha_retiro)
SELECT DISTINCT 
    Victima.id_victima,
    Ubicacion.ID_UBICACION,
    TEMPORAL.FECHA_LLEGADA,
    TEMPORAL.FECHA_RETIRO
FROM Temporal, Ubicacion, victima 
WHERE 
    TEMPORAL.UBICACION_VICTIMA = Ubicacion.ubicacion and
    TEMPORAL.NOMBRE_VICTIMA  = Victima.nombre AND 
    TEMPORAL.APELLIDO_VICTIMA  = Victima.APELLIDO 
    ;

DELETE FROM LUGAR_VICTIMA lv2 ;
SELECT count(*) FROM LUGAR_VICTIMA lv ;
SELECT * FROM Lugar_victima ORDER BY ID_LUGARVICTIMA ;

----------------------------------------
-- Insertar Allegado_victima--
----------------------------------------
INSERT INTO ALLEGADO_victima(id_victima,id_allegado,id_tipocontacto,fecha_inicio_contacto,fecha_fin_contacto, fecha_conocio)
SELECT DISTINCT 
    Victima.id_victima,
    Allegado.id_allegado,
    Tipo_contacto.id_tipocontacto,
    TEMPORAL.FECHA_INICIO_CONTACTO,
    TEMPORAL.FECHA_FIN_CONTACTO,
    TEMPORAL.FECHA_CONOCIO
FROM temporal,Victima,Allegado,TIPO_CONTACTO
WHERE 
    TEMPORAL.NOMBRE_VICTIMA = VICTIMA.NOMBRE  AND
    temporal.APELLIDO_VICTIMA = victima.APELLIDO AND
    TEMPORAL.NOMBRE_ASOCIADOF = ALLEGADO.NOMBRE  AND
    temporal.APELLIDO_ASOCIADO = allegado.APELLIDO AND 
    TEMPORAL.CONTACTO_FISICO = TIPO_CONTACTO.TIPO_CONTACTO  ;
   
SELECT * FROM Allegado_victima ORDER BY id_allegadovictima;
DELETE FROM ALLEGADO_VICTIMA;
SELECT COUNT(*) FROM ALLEGADO_VICTIMA ; 
--CONSULTAS**********************************************************
--1
SELECT  h.nombre AS Hospital,u.UBICACION, COUNT(v.id_victima) AS Fallecidos
FROM Hospital h
LEFT JOIN Ubicacion u ON h.id_ubicacion = u.id_ubicacion --relaciona la ubicacion con el id ubicacion de hospital 
JOIN REGISTRO hv ON h.id_hospital = hv.id_hospital --obtiene todos los registros donde id hospital esta relacionado
JOIN Victima v ON hv.id_victima = v.id_victima --obtiene todas las victimas del resultado anterior en hospital-victima(registro) esta relacionada
WHERE v.fecha_muerte IS NOT NULL
GROUP BY  u.UBICACION ,h.nombre ORDER BY Fallecidos desc;--ACONSEJABLE SIEMPRE HACER GROUP BY LUEGO DE LOS JOINS

--2
SELECT  v.NOMBRE ,v.APELLIDO, v.STATUS_ENFERMEDAD, vt.EFECTIVIDAD_EN_VICTIMA
FROM VICTIMA v 
--conectar con victima con victima-tratamiento y obtener solo el que cumple
JOIN VICTIMA_TRATAMIENTO vt ON v.ID_VICTIMA  = vt.ID_VICTIMA 
--conectar victima-tratamiento filtrado con el join anteior con tratamiento 
JOIN TRATAMIENTO t ON vt.ID_TRATAMIENTO = t.ID_TRATAMIENTO 
WHERE V.STATUS_ENFERMEDAD  = 'En cuarentena' AND T.NOMBRE = 'Transfusiones de sangre' AND vt.EFECTIVIDAD_EN_VICTIMA >5
;
--3
--NOMBRE APELLIDO DIRECCION CON MAS DE 3 ASOCIADOS
SELECT v.NOMBRE, V.APELLIDO , u.Ubicacion, COUNT(av.ID_ALLEGADO) AS ALLEGADOS 
FROM VICTIMA v 
JOIN UBICACION u ON u.ID_UBICACION =v.ID_DIRECCION 
JOIN ALLEGADO_VICTIMA av ON av.ID_VICTIMA = V.ID_VICTIMA 
WHERE v.FECHA_MUERTE IS not NULL 
GROUP BY v.NOMBRE , V.APELLIDO, U.UBICACION 
HAVING COUNT(DISTINCT av.ID_ALLEGADO) > 3  ORDER BY allegados ; 
--4
--Mostrar el nombre y apellido de todas las víctimas en estado 
--“Suspendida” que tuvieron contacto físico de tipo “Beso” con más
--de 2 de sus asociado
SELECT v.NOMBRE, V.APELLIDO ,v.STATUS_ENFERMEDAD 
FROM VICTIMA v 
JOIN ALLEGADO_VICTIMA av ON av.ID_VICTIMA = V.ID_VICTIMA
JOIN TIPO_CONTACTO tc ON tc.ID_TIPOCONTACTO  = av.ID_TIPOCONTACTO 
WHERE v.STATUS_ENFERMEDAD = 'Suspendida' AND tc.TIPO_CONTACTO ='Beso'
GROUP BY v.NOMBRE , V.APELLIDO, v.STATUS_ENFERMEDAD 
HAVING COUNT(DISTINCT av.ID_ALLEGADO) > 2 ; 
--5
--Top 5 de víctimas que más tratamientos se han aplicado del 
--tratamiento “Oxígeno”
SELECT v.NOMBRE ,V.APELLIDO ,t.NOMBRE , COUNT(vt.ID_P_TRATAMIENTO) AS Tratamientos
FROM VICTIMA v 
JOIN VICTIMA_TRATAMIENTO vt ON vt.ID_VICTIMA = v.ID_VICTIMA 
JOIN  TRATAMIENTO t ON t.ID_TRATAMIENTO =vt.ID_TRATAMIENTO 
WHERE t.NOMBRE ='Oxigeno'
GROUP  BY v.NOMBRE ,t.NOMBRE ,v.APELLIDO ORDER BY Tratamientos
FETCH FIRST 5 ROWS ONLY;
--6
--Mostrar el nombre, el apellido y la fecha de fallecimiento de todas las 
--víctimas que se movieron por la dirección “1987 Delphine Well” a los 
--cuales se les aplicó "Manejo de la presión arterial" como tratamiento.
SELECT v.NOMBRE, V.APELLIDO , V.FECHA_MUERTE  
FROM  VICTIMA v 
JOIN VICTIMA_TRATAMIENTO vt ON vt.ID_VICTIMA =v.ID_VICTIMA 
JOIN TRATAMIENTO t ON t.ID_TRATAMIENTO =vt.ID_TRATAMIENTO 
JOIN LUGAR_VICTIMA lv ON LV.ID_VICTIMA = V.ID_VICTIMA 
JOIN UBICACION u ON U.ID_UBICACION = LV.ID_UBICACION 
WHERE u.UBICACION ='1987 Delphine Well' AND t.NOMBRE = 'Manejo de la presion arterial';

--7
--Mostrar nombre, apellido y dirección de las víctimas que tienen menos 
--de 2 allegados, las victimas han de haber estado en un hospital y que se le 
--hayan aplicado únicamente dos tratamientos
SELECT  V.NOMBRE ,v.APELLIDO , u.UBICACION 
FROM VICTIMA v 
JOIN UBICACION u ON u.ID_UBICACION =v.ID_DIRECCION 
JOIN VICTIMA_TRATAMIENTO vt ON v.ID_VICTIMA  =vt.ID_VICTIMA 
JOIN REGISTRO r ON V.ID_VICTIMA = r.ID_VICTIMA 
JOIN ALLEGADO_VICTIMA av ON v.ID_VICTIMA = av.ID_VICTIMA
GROUP BY v.ID_VICTIMA , v.NOMBRE ,v.APELLIDO ,u.UBICACION  --HAVING SOLO SE PUEDE USAR DESPUES DE UN GROUP BY 
--NO SE PUEDE USAR COUNT EN UN WHERE PARA ESO SE USA UN HAVING 
--WHERE COUNT(av.ID_ALLEGADO)>2 AND COUNT(vt.ID_P_TRATAMIENTO) > 2;  
HAVING COUNT(DISTINCT av.ID_ALLEGADO)<2 AND COUNT(DISTINCT vt.ID_TRATAMIENTO) = 2;  

--8
--Mostrar el número de mes de la fecha de la primera sospecha, 
--nombre y apellido de las víctimas que más tratamientos se han 
--aplicado y las que menos. (Todo en una misma consulta)
SELECT v.NOMBRE, V.APELLIDO, EXTRACT(MONTH FROM V.FECHA_PRIMERA_SOSPECHA) AS MES_SOSPECHA, COUNT(vt.ID_P_TRATAMIENTO) AS N_tratamientos
FROM  VICTIMA v 
JOIN VICTIMA_TRATAMIENTO vt ON vt.ID_VICTIMA =v.ID_VICTIMA 
GROUP BY v.NOMBRE , V.APELLIDO,EXTRACT(MONTH FROM v.FECHA_PRIMERA_SOSPECHA) 
HAVING COUNT(*) = (
  SELECT MAX(N_TRATAMIENTOS) --busca el tratamiento maximo en una subconsulta que devuelve el numero de tratamientos DE CADA VICTIMA
  FROM (
    SELECT COUNT(*) AS N_TRATAMIENTOS  --SUBCONSULTA QUE DEVUELVE EL NUMERO DE TRATAMIENTOS PARA UNA VICTIMA
    FROM Victima V
    JOIN VICTIMA_TRATAMIENTO vt2  ON V.ID_VICTIMA  = vt2.ID_VICTIMA 
    GROUP BY v.NOMBRE ,v.APELLIDO 
  )
) UNION --COLOCA UNA TABLA DEBAJO DE LA OTRA (ASEGURARSE QUE TENGA MISMAS COLUMNAS CASO CONTRARIO DARA ERROR)
SELECT v.NOMBRE, V.APELLIDO, EXTRACT(MONTH FROM V.FECHA_PRIMERA_SOSPECHA) AS MES_SOSPECHA, COUNT(vt.ID_P_TRATAMIENTO) AS N_tratamientos
FROM  VICTIMA v 
JOIN VICTIMA_TRATAMIENTO vt ON vt.ID_VICTIMA =v.ID_VICTIMA 
GROUP BY v.NOMBRE , V.APELLIDO,EXTRACT(MONTH FROM v.FECHA_PRIMERA_SOSPECHA) 
HAVING COUNT(*) = (
  SELECT MIN(N_TRATAMIENTOS) --busca el tratamiento MINIMO en una subconsulta que devuelve el numero de tratamientos DE CADA VICTIMA
  FROM (
    SELECT COUNT(*) AS N_TRATAMIENTOS --SUBCONSULTA QUE DEVUELVE EL NUMERO DE TRATAMIENTOS PARA UNA VICTIMA 
    FROM Victima V
    JOIN VICTIMA_TRATAMIENTO vt2  ON V.ID_VICTIMA  = vt2.ID_VICTIMA 
    GROUP BY v.NOMBRE ,v.APELLIDO 
  )
) ORDER BY N_TRATAMIENTOS  DESC;

--9
--Mostrar el porcentaje de víctimas que le corresponden a cada 
--hospita
SELECT h.NOMBRE, (COUNT(R.ID_REGISTRO)/(SELECT COUNT(*) FROM VICTIMA)*100) AS PORCENTAJE, COUNT(R.ID_REGISTRO) AS N_REGISTROS
FROM HOSPITAL h 
JOIN REGISTRO r ON R.ID_HOSPITAL =H.ID_HOSPITAL 
GROUP BY h.NOMBRE ;

--10
-- Mostrar el porcentaje del contacto físico más común de cada 
-- hospital de la siguiente manera: nombre de hospital, nombre del 
-- contacto físico, porcentaje de víctimas

SELECT h.NOMBRE , c.TIPO_CONTACTO , 
(COUNT(DISTINCT v.id_Victima) / (SELECT COUNT(*) FROM Victima) * 100) AS porcentaje
FROM Hospital h
JOIN  REGISTRO rh ON h.id_Hospital = rh.id_Hospital
JOIN Victima v ON rh.id_Victima = v.id_Victima
JOIN ALLEGADO_VICTIMA la ON v.id_Victima = la.id_Victima
JOIN TIPO_CONTACTO  c ON la.ID_TIPOCONTACTO  = c.ID_TIPOCONTACTO 
WHERE rh.id_Victima IN (
    SELECT id_Victima FROM ALLEGADO_VICTIMA
    WHERE id_TIPOCONTACTO = (
        SELECT ID_TIPOCONTACTO  FROM (
            SELECT id_TIPOCONTACTO, COUNT(*) cnt
            FROM ALLEGADO_VICTIMA av 
            GROUP BY id_TIPOCONTACTO
            ORDER BY cnt DESC
            FETCH FIRST 1 ROW ONLY
        )
    )
)
GROUP BY h.NOMBRE , c.TIPO_CONTACTO ;



