--Tabla Hospital
CREATE TABLE Hospital (
    id_hospital INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(60),
    id_ubicacion int, 
    PRIMARY KEY (id_hospital)
    FOREIGN KEY (id_ubicacion) REFERENCES Ubicacion(id_ubicacion) 
);
--Tabla Registro (Hospital-victima)
CREATE TABLE Registro(
    id_registro INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_hospital int,
    id_victima int,
    PRIMARY KEY(id_registro),
    FOREIGN KEY (id_hospital) REFERENCES Hospital(id_hospital) ,
    FOREIGN KEY (id_victima) REFERENCES victima(id_victima) 
);

--Tabla victima 
CREATE TABLE Victima (
    id_victima INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(60),
    apellido VARCHAR(60),
    id_direccion int,
    fecha_primera_sospecha date,
    fecha_confirmacion date,
    fecha_muerte date,
    status_enfermedad VARCHAR(50),
    PRIMARY key(id_victima),
    FOREIGN KEY (id_ubicacion) REFERENCES Ubicacion(id_ubicacion),
);
--victima-tratamiento
CREATE TABLE victima_tratamiento(
    id_p_tratamiento INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_victima int,
    id_tratamiento int,
    efectividad_en_victima int,
    FECHA_INICIO_TRATAMIENTO DATE,
    FECHA_FIN_TRATAMIENTO DATE
    PRIMARY KEY(id_p_tratamiento)
    FOREIGN KEY (id_victima) REFERENCES victima(id_victima),
    FOREIGN KEY (id_tratamiento) REFERENCES Tratamiento(id_tratamiento)
);

--Tratamiento
CREATE TABLE Tratamiento (
    id_tratamiento INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50),
    efectividad int
    PRIMARY KEY(id_tratamiento)
);

--Lugar_victima  (lugares que un victima visito)
CREATE TABLE Lugar_victima(
    id_ubicacion int,
    id_victima int,
    fecha_llegada date,
    fecha_retiro date,
    FOREIGN KEY (id_ubicacion) REFERENCES Ubicacion(id_ubicacion),
    FOREIGN KEY (id_victima) REFERENCES victima(id_ubicacion)
);

--Ubicacion
CREATE TABLE Ubicacion(
    id_ubicacion INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ubicacion VARCHAR(60),
    PRIMARY KEY(id_ubicacion)
);

--Contacto (Allegado victima)
CREATE Table Contacto(
    id_contacto INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_victima int,
    id_allegado int,
    id_tipocontacto int,
    fecha_conocio date,
    fecha_inicio_contacto date,
    fecha_fin_contacto date,
    PRIMARY KEY(id_contacto)
    FOREIGN KEY (id_victima) REFERENCES victima(id_victima),
    FOREIGN KEY (id_allegado) REFERENCES Allegado(id_allegado),
    FOREIGN KEY (id_tipocontacto) REFERENCES Tipo_contacto(id_tipocontacto)
);
--tipo contacto
CREATE Table Tipo_contacto(
    id_tipocontacto INTEGER GENERATED BY DEFAULT AS IDENTITY,
    tipo_contacto VARCHAR(50),
    PRIMARY key(id_tipocontacto)
);

--Allegado
CREATE Table Allegado(
    id_allegado INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50),
    apellido VARCHAR(50),
    PRIMARY KEY(id_allegado)
);