--Tabla Hospital
CREATE TABLE Hospital (
    id_hospital INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(60),
    id_ubicacion int, 
    PRIMARY KEY (id_hospital)
    FOREIGN KEY (id_ubicacion) REFERENCES Ubicacion(id_ubicacion) 
);
--Tabla Registro (Hospital-Paciente)
CREATE TABLE Registro(
    id_registro INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_hospital int,
    id_paciente int,
    PRIMARY KEY(id_registro),
    FOREIGN KEY (id_hospital) REFERENCES Hospital(id_hospital) ,
    FOREIGN KEY (id_paciente) REFERENCES Ubicacion(id_paciente) 
);

--Tabla paciente 
CREATE TABLE Paciente (
    id_paciente INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombres VARCHAR(60),
    apellidos VARCHAR(60),
    id_ubicacion int,
    fecha_primera_sospecha date,
    fecha_confirmacion date,
    fecha_registro_llegada date,
    fecha_retiro date,
    fecha_muerte date,
    status_enfermedad VARCHAR(50),
    PRIMARY key(id_paciente),
    FOREIGN KEY (id_ubicacion) REFERENCES Ubicacion(id_ubicacion),
);
--Paciente-tratamiento
CREATE TABLE Paciente_tratamiento(
    id_p_tratamiento INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_paciente int,
    id_tratamiento int,
    efectividad_en_paciente int,
    PRIMARY KEY(id_p_tratamiento)
    FOREIGN KEY (id_paciente) REFERENCES Paciente(id_paciente),
    FOREIGN KEY (id_tratamiento) REFERENCES Tratamiento(id_tratamiento)
);

--Tratamiento
CREATE TABLE Tratamiento (
    id_tratamiento INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50),
    efectividad int
    PRIMARY KEY(id_tratamiento)
);

--Lugar_paciente  (lugares que un paciente visito)
CREATE TABLE Lugar_paciente(
    id_ubicacion int,
    id_paciente int,
    fh_entrada date,
    fh_salida date,
    FOREIGN KEY (id_ubicacion) REFERENCES Ubicacion(id_ubicacion),
    FOREIGN KEY (id_paciente) REFERENCES Paciente(id_ubicacion)
);

--Ubicacion
CREATE TABLE Ubicacion(
    id_ubicacion INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ubicacion VARCHAR(60),
    PRIMARY KEY(id_ubicacion)
);

--Contacto (Allegado Paciente)
CREATE Table Contacto(
    id_contacto INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_paciente int,
    id_allegado int,
    id_tipocontacto int,
    fh_inicio date,
    fh_fin date,
    PRIMARY KEY(id_contacto)
    FOREIGN KEY (id_paciente) REFERENCES Paciente(id_paciente),
    FOREIGN KEY (id_allegado) REFERENCES Allegado(id_allegado),
    FOREIGN KEY (id_tipocontacto) REFERENCES Tipo_contacto(id_tipocontacto)
);
--tipo contacto
CREATE Table Tipo_contacto(
    id_tipocontacto INTEGER GENERATED BY DEFAULT AS IDENTITY,
    t_contacto VARCHAR(50),
    PRIMARY key(id_tipocontacto)
);

--Allegado
CREATE Table Allegado(
    id_allegado INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombres VARCHAR(50),
    apellidos VARCHAR(50),
    fecha_conocerse date,
    PRIMARY KEY(id_allegado)
);